### ISSUE TITLE
Limit on Usage of Craftable Items

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#119]
**Describe the solution you'd like**
A suggestion from Discord:
A way to put stats on items such that if something can be/is made from them, you can limit usage of that by skills.

Ex:
Gold bars have a crafted item requirement of `"crafting": 35` on them. 
Sticks have a crafted item requirement of `"woodcutting": 15` on them.
You get a golden axe. If you don't have `crafting` skill 35 and `woodcutting` skill 15, the golden axe cannot be used for anything.

**Why is this feature needed**
A new way to limit usage by tech tree based on crafted components.

**Describe alternatives you've considered**
Rather than block usage completely, allow for effects to be added.

**Comment by Caltinor** [comment]
This is a big ole nope from me.  Here's why.  The first issue has to do with reverse engineering recipes.  Technologically you would have to go through every recipe to obtain the output item, then cache the components so that you can later aggregate their collective requirements.  The second part has to do with multiple recipes.  Suppose you gate gold ingots and sticks like you have, but I add a recipe to make a golden axe out of glowstone and end rods (ooh magic golden axe).  glowstone and end rods don't have reqs so I can't use the item because another recipe has reqs?  it gets messy and puts the burden on pack makers to manage all recipes added by mods where duplications exist.

This is a very doable feature though.  and the API has all the tools an addon would need to make it a reality.  It's just a very burdensome feature to include in core PMMO.

**Comment by SomewhatDamaged** [comment]
No problems. Figured it might be something like that, but thought it best to toss it in here in case there was some neat and easy way to do it I wasn't seeing. Thanks again for entertaining the idea.
