### ISSUE TITLE
Shovels Require Mining Skill Instead of Excavation

### ISSUE THREAD

**Issue by CheezBallzFTW** [Caltinor/Project-MMO-2.0#129]
**Describe the bug**
All the modded shovels have a Mining skill requirement instead of an Excavation skill requirement.

**Expected behavior**
The shovels should require Excavation skill like the vanilla shovels correctly do.

**To Reproduce**
1. Have a shovel added from a mod.
2. Check the shovel in the creative menu or jei.

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.1.47
 - PMMO: 1.19.2-0.5.5

**Comment by Caltinor** [comment]
could you please provide an example mod where this occurs?

**Comment by SomewhatDamaged** [comment]
Can confirm that [`Mekanism: Tools`](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools) shovels have this issue.

![image](https://user-images.githubusercontent.com/6394544/200558473-e3e262df-1f1a-4f82-839b-0bac456b1170.png)

**Comment by Caltinor** [comment]
oh! right, this is working as intended.  All AutoValue item tool reqs us this property
![image](https://user-images.githubusercontent.com/62700786/200581130-bc51ed57-ed27-4e60-8650-588e29c42ce1.png)

That said, AutoValues could use a slight expansion to set skills for the different tool types.  That is a sensible expansion that won't be breaking.  I'm going to slate that for 1.1.0 though so that will come in the release following 1.0.0 (which is coming next)
