### ISSUE TITLE
Agility Always Displayed

### ISSUE THREAD

**Issue by Tyrius1** [Caltinor/Project-MMO-2.0#18]
**Describe the bug**
Agility is always displayed even when experience is 0

**Expected behavior**
For agility to only be displayed in skills list on top left of screen when agility experience has been gained.

**To Reproduce**
1. set all xp gains to 0.0
2. join game and move around a little
3. agility xp does not increase but does show up in skills menu

**Screenshots**
![2022-06-18_18 39 36](https://user-images.githubusercontent.com/29525146/174459196-ed8e54c6-5ecb-414c-b657-15d00a102317.png)

**Versions:**
 - Minecraft: 1.19
 - pmmo-1.19-0.0.4.jar

**Additional context**
Removing the entries does prevent the agility skill from being displayed on top left so perhaps this isn't really an issue...

**Comment by Caltinor** [comment]
Is this still an issue?  If it is, let me make sure I understand this properly:

- You have set agility xp in the server-config to zero so that all normal agility gaining actions give no xp.
  - However if you remove the agility entry completely, the issue goes away
- Even though no xp is gained, Agility shows at the top left of the screen

Followup questions, if you changed the skill name in the config from agility to something else, like combat instead but kept the value at zero, would combat have this same persistence effect?

If you don't get to testing this yourself, I will, but wasn't sure if you had tried or not.

**Comment by Tyrius1** [comment]
Tested by changing the following entries to combat = 0.0

			[XP_Gains.Event_XP_Specifics.Jumps."SPRINT_JUMP Skills and Ratios"]
				combat = 0.0

			[XP_Gains.Event_XP_Specifics.Player_Actions."SPRINTING Skills and Ratios"]
				combat = 0.0

Combat is displayed in the skill list as 0.0 after sprint jumping around a bit in creative so looks like it's the same that way too
![2022-06-18_21 35 27](https://user-images.githubusercontent.com/29525146/174462277-0be83a1f-4feb-4e21-9d6a-bc3cf9699e5f.png)
.

**Comment by Caltinor** [comment]
Awesome!  Thank you. This helps a ton.  I marked this a QOL but I think the fix is easy enough to squeak into the next release.
