### ISSUE TITLE
Vein Mining no working 1.18.2

### ISSUE THREAD

**Issue by samjviana** [Caltinor/Project-MMO-2.0#183]
**Describe the bug**
Vein mining is not working, when i hold the vein mine button it shows the blocks that would be vein mined, but when i do mine nothing happens.

**Expected behavior**
Hold the vein mine bind and then mine the block, it should brake every connected block (as long as it is in the whitelist, and the "skill" is filled

**To Reproduce**
1. Try to use vein mine

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.1.20
 - PMMO: 1.18.2-5.1.1

**Comment by Caltinor** [comment]
Please expand your reproduction steps.  This give me no indication of the context with which you attempted to vein mine.  Were you holding a tool? what block were you attempting to break?  how much charge did you have? were you in survival mode? are you using any other mods?

If I followed your exact reproduction steps in a brand new world, i would in fact not be able to vein mine because out would have no items and no charge.

**Comment by samjviana** [comment]
i`m using a stone pickaxe 
trying to mine coal ore
the vein gauge don't show up, even if i press the "Toggle Vein Gauge"
in survival mode
i'm using other mods, but tested with only pmmo and had the same thing

i remember that pmmo had a whilelist ... but i couldn't find

**Comment by Caltinor** [comment]
You mentioned that you could see the outlines around the blocks that should have been veined.  is that correct?

**Comment by samjviana** [comment]
yeah

**Comment by Caltinor** [comment]
Something else is going on then.  I was able to vein mine using the exact steps you provided.
1. created a new world with only PMMO
2. gave myself lvl10 mining to use the pickaxe
3. marked the block
4. observed the blocks to be veined
![2023-01-14_13 35 52](https://user-images.githubusercontent.com/62700786/212490423-4b197f0b-13e4-40f3-900b-7fa1779a2007.png)
5. broke the marked block
6. Vein consumed, blocks broken, drops dropped
![2023-01-14_13 35 58](https://user-images.githubusercontent.com/62700786/212490541-df075947-66cf-4e4f-a66a-1344c563c8e5.png)

**Comment by samjviana** [comment]
🤔🤔 i'll try to reinstall everything (minecraft, forge and mods) ... brb

**Comment by samjviana** [comment]
don't know what was wrong ... but reinstalling did the trick
it's not perfect since the gauge stays X/0 ... but is working
is there a way for me to whitelist mod ores? or add new tools to the veinmining, like tinker`s tools?
or should i open another issue for this

**Comment by Caltinor** [comment]
I think you misunderstand how vein mining works.  

1. all blocks can be vein mined.  Your only other option is to blacklist them at the biome or dimension level.  
2. the "X/0" is "currentCharge/MaxCharge" which means you are overcharged and wont regenerate what you have since your capacity is zero.
3. Vein ability is given from items.  You'll notice that wooden tools will charge your vein, but netherite ones do not.  All vein charge rates and capacities are governed by items held and worn.
4. All tools are capable of vein mining, but not all tools provide charge or recharge, so design around that.
