### ISSUE TITLE
Blocking XP Not Awarded

### ISSUE THREAD

**Issue by Tyrius1** [Caltinor/Project-MMO-2.0#19]
**Describe the bug**
With shield block set to give endurance: 100 on zombie they are giving 0 xp instead.

**Expected behavior**
That you would gain endurance xp based on the amount of damage blocked. 

**To Reproduce**
1. Set         "SHIELD_BLOCK": { "endurance": 100 }
2. spawn zombie and let it hit you while you are blocking
3. gain 0 endurance experience

**Screenshots**
![image](https://user-images.githubusercontent.com/29525146/174463349-16a40df3-4575-4815-acd7-c6d80be9e441.png)

**Versions:**
 - Minecraft: 1.19
 - pmmo-1.19-0.0.4.jar

**Additional context**
The other entries here are working as expected.

**Comment by Caltinor** [comment]
So this actually wasn't a bug, but I changed it anyways.  

The way the event worked was that the shield itself has the shield block XP value not the damage source.  That was obviously not very intuitive and also limited the amount of variability you could get from block actions.  I also had the Shield_Block property as being tagged as an entity event in the code, which means I probably at some level had that same thought. 

The next update will include a change to the shield block declaration.  Since this affects existing configurations, this will result in a minor version change, bumping us to 0.1.0.
