### ISSUE TITLE
pmmo_saved_data.PmmoSavedData.func_189551

### ISSUE THREAD

**Issue by robtbs** [Caltinor/Project-MMO-2.0#228]
**Describe the bug**
[Describe exactly what you observed](https://paste.gg/p/anonymous/dfdeb55a850b49a799e85fe1997d4e67)

**Expected behavior**
the server crashes 

**Versions:**
 - Minecraft: 1.16.5
 - Loader: 36.2.39
 - PMMO: [Project_MMO-1.16.5-3.68.0

**Additional context**

**Comment by Caltinor** [comment]
That's a crash log Alright.  Please edit your issue to confirm to the format. Explain what the issue is as you observed it. Explain what you expect to happen. And most importantly how we as developers can reproduce the issue. You seemed to have deleted that portion of the template. Once you have added reproduction steps, we will investigate.
