### ISSUE TITLE
Weird double jumping bug

### ISSUE THREAD

**Issue by Amaradis** [Caltinor/Project-MMO-2.0#234]
**Describe the bug**
My character double jumps randomly, I think its a bug because these is no where to turn this feature off, not even in the config.

**Expected behavior**
To not double jump and get flung several blocks in a random direction

**To Reproduce**
Sprint while jumping

**Screenshots**

**Versions:**
1.18.2
Mod version 1.18.2-3.69.9

**Comment by SomewhatDamaged** [comment]
This is due to latency (time it takes for data to reach you from the server).

The problem has been fixed in the latest version, but if you wish to continue using 3.69.9 you will need to edit `minecraft/config/pmmo/perks.json` and remove the following section:

![image](https://user-images.githubusercontent.com/6394544/222937711-c1e399cb-377d-4aaf-996b-5403f29db785.png)

Just delete everything highlighted there on the server and restart it.

**Comment by Amaradis** [comment]
Thanks so much, that was driving me crazy lol.

**Comment by SomewhatDamaged** [comment]
No problems!
