### ISSUE TITLE
genData Command Option to Populate With Current Values

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#288]
**Describe what this tool does, conceptually:**  (not the how, just the outputs)
An option for `/pmmo genData` that would fill in all the current values for items based on what the game's current configuration is. This would be a mix of what current datapacks are loaded, the built-in data, and also what AutoValues reports.

Perhaps a further option to specify what sources to use to create the data: 
`all`: as above, everything is rolled up
`autoValues`: populates with all the data settings from AutoValues
`datapacks`: populates with all the current datapacks' data
`internal`: populates only with the internal datapack

The three non `all` values could be done incrementally, so run `autoValues` first and then `internal` second would result in what a plain, first-install version of PMMO would have.

**Describe how current configuration methods are insufficient for the task:**
To give users a starting point and an understanding of the numbers involved. 

**What platform would you like to see this tool on:**
In-game.

**Comment by Caltinor** [comment]
So, this is mostly possible.  The only hiccup is with AutoValues.  Those only generate when the item is used.  buuuut... i'm pretty sure the data generator does iterate over every item, so i probably could.  So, yeah this should be possible.  The only potential downside is that it would effectively negate the entire AutoValue system since items would now have configurations instead of AutoValues which means any tweaks to autovalues after the fact would have no effect.
