### ISSUE TITLE
Jumping and Pausing with proper timing causes Agility exp to be gained while in the pause menu.

### ISSUE THREAD

**Issue by Quinndaline** [Caltinor/Project-MMO-2.0#31]
**Describe the bug**
While playing in single player I had jumped and pressed esc at the same time, I left and came back 20 minutes later with about 19 levels of agility exp given to me after exiting the pause menu. 

**Expected behavior**
I expected to not have received almost 19 levels of free agility exp for pausing the game. 

**To Reproduce**
1. Jump in Singe Player
2. Press esc to enter the pause menu
3. Wait for agility exp to accumulate
4. Press esc again to exit the pause menu and automatically receive agility exp

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge 40.1.47
 - PMMO: 1.18.2-3.69.11

**Additional context**
This bug is super inconsistent and I am not 100% sure as to why it happened but I theorize that it must be timed so that you pause on the same tick that you would normally gain agility exp on or possibly the tick beforehand. As long as you are paused it will just keep adding exp and then give it to you all at once as soon as you unpause the game.

**Comment by Caltinor** [comment]
So this is actually a known behavior.  We have the same thing with swimming if you go under water and pause the game.  The reason this occurs is because the client still ticks even if the server is paused.  This means that certain events still run even if the game is paused and xp will accumulate.  

That said, this does not occur in multiplayer because the server cannot be paused.  Because of this, Harmony decided that it was not worth fixing since it's essentially a singleplayer cheat that doesn't impact servers and is therefore only affects the player   who is using it.  We are not in the business of policing singleplayer behavior.  It is up to you to not exploit this, unless you want to.

**Comment by Harmonised7** [comment]
Yikes I feel lazy now >w< But that's accurate.
