### ISSUE TITLE
[1.19.2] Death XP Loss

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#317]
**Describe the bug**
Setting `"Loss on death" = 1.0` and `"Lose Levels On Death" = true` doesn't have the intended action of scrubbing all skills when the player dies.

**Expected behavior**
Setting `"Loss on death" = 1.0` and `"Lose Levels On Death" = true` should mean you lose all your levels every time you die.

**To Reproduce**
1. Create new game
2. Give some XP
3. Exit and add applicable settings
4. Load up
5. Die
6. Still have levels

**Screenshots**

**Versions:**
 - Minecraft: 1.19.2 (probably others that have the same code)
 - Loader: Forge-43.2.11
 - PMMO: 1.19.2-3.1.2

**Additional context**
| ||
|| |_

**Comment by Ncheung-sp** [comment]
https://youtu.be/axIFqKUewVo

I hope this helps. The "lose level on Death" option doesn't seem to be having any effect. I used the Configured mod because it's practical, but I've tried it in several ways, like editing pmmo-server directly, closing the game, editing with the game open, I've done everything and the effect is the same. It doesn't work as suggested that it would at least lose the current XP and go back one level down, in this case, the excavation level should have gone back to level 1. But what I really wanted was for everyone to go back to zero.

**Comment by SomewhatDamaged** [comment]
Ah, I see the issue.

This code grabs the value, checks if it is `1.0` and, if so, sets `lossRatio` to `1.0`

Otherwise it sets `lossRatio` to `1 - LOSS_ON_DEATH`

https://github.com/Caltinor/Project-MMO-2.0/blob/306fdad8c3ab8f3ef913c7347261618d38e04450/src/main/java/harmonised/pmmo/events/impl/PlayerDeathHandler.java#L16-L18

Then, since `LOSE_LEVELS_ON_DEATH` is `true`, the `else` block executes.

This sets the xp to `losableXp * lossRatio` and since `lossRatio` is `1.0`, it literally sets the XP to the `losableXp` value.

https://github.com/Caltinor/Project-MMO-2.0/blob/306fdad8c3ab8f3ef913c7347261618d38e04450/src/main/java/harmonised/pmmo/events/impl/PlayerDeathHandler.java#L43

Perhaps an exception needs to be made explicitly for when loss is `1.0` ~ line 43?
