### ISSUE TITLE
XP incompatability between Project MMO and other mods

### ISSUE THREAD

**Issue by Devilswarchild** [Caltinor/Project-MMO-2.0#325]
MC 1.20.1
Forge Version 47.1.3
project mmo version: pmmo-1.20.1-1.0.2.jar

It has been brought to my attention that Project MMO is behaving in aa slightly weird way towards xp for certain actions when tree harvester and reap mod are present in any modpack.
might also be affected in the future in the same way with Ore Excavation if it ever comes to 1.20.1
This is just a compat report in the hopes that it can be rectified in some way.

for instance, with tree harverster and reap mod( idk if reap is actually doing anything with xp though) when you use the axe to break one block so the whole tree falls, players are getting mining xp instead of woodcutting xp.

steps to reproduce:

have tree harvester and reap mod installed alongside project mmo
cut down a tree with an axe
rinse and repeat.

![Screenshot_3](https://github.com/Caltinor/Project-MMO-2.0/assets/27385258/418876c1-11df-4aa7-959d-9f9252e09b50)

**Comment by SomewhatDamaged** [comment]
The issue with Tree Harvester has already been reported to their GIT: https://github.com/ricksouth/serilum-mc-mods/issues/1873

**Comment by Caltinor** [comment]
@Devilswarchild as stated above, I already talked to the dev for Tree Harvester and they stated they needed to restore functionality they removed for techinical reasons.  I created the issue [here](https://github.com/ricksouth/serilum-mc-mods/issues/1873).  As for Reap, most right-click-harvest (RCH) mods don't fire Forge events for `break` and `place` as they should.  As such, there is no way for PMMO to know that the blocks were harvested and to subsequently award XP.  I have reached out to multiple devs about adding this functionality, but most of them either don't understand events and/or don't care.  I generally just recommend users accept that there is a tradeoff between XP and efficiency because of this.  As for Ore Excavation, as long as it fires events like it should (either directly or by using methods that do already) you should be fine.  Tree harvest was a unique case in terms of the conditions that broke the compat.
