### ISSUE TITLE
New Perk Event: Standing Still | Standing Still Crouched

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#366]
**Describe the solution you'd like**
A perk event that is fired for standing still either crouched or upright. Probably mostly only useful in conjunction with the delay perk attribute feature request.

**Why is this feature needed**
It might be cool if there was a perk that could be activated for standing still for a certain amount of time. Like regeneration or mana regen in ars nouveau after 30 seconds of being upright and not moving. A meditation of sorts. It's not high priority so if you're not into it no worries.

**Describe alternatives you've considered**
None

**Comment by Caltinor** [comment]
This is a good candidate for my planned event context system update.  Additionally, I need to find a way to capture behavior-over-time so that events that rely on duration of behavior not just instances of behavior can be captured.  Closing this for now and we can reconsider when I have that system in place.
