### ISSUE TITLE
Boss Mob Scaling

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#372]
**Describe the solution you'd like**
A way to modify the mob scaling so that boss monsters (Wither, End Dragon, Warden, etc) are scaled relative to existing mobs.

**Why is this feature needed**
Because a Wither cannot kill `combat` 150 spawned skeletons, and in fact will get killed by them.

**Describe alternatives you've considered**
Mobbing the End Dragon with Endermen.

**Comment by Caltinor** [comment]
what about a tag like "pmmo:scaling_exempt"?

**Comment by SomewhatDamaged** [comment]
That sort of does the opposite. "pmmo:scale" or even a setting in `pmmo-server.toml` to `"Apply Scaling to Bosses" = 0.0` to set how much scaling is applied to them.

**Comment by Caltinor** [comment]
oh, i was going off discord and didn't fully read this.  🤔 i don't know that I want mobs to scale off anything other than the player.  It's a feature that doesn't overtly appear to be in scope of pmmo.  I would be amenable to a scale for bosses via config that is applied on top of their normal scaling so that they are differentiated somehow.  would still want a tag so "boss" isn't hardcoded.
