### ISSUE TITLE
Spelling Mistake in AutoValues.toml Generator

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#398]
**Describe the bug**
Block `BREAK` and `PLACE` autovalues are not calculating. I believe the issue is that the value being used is `BLock` rather than `Block`:

https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main/java/harmonised/pmmo/features/autovalues/AutoValueConfig.java#L213

**Expected behavior**
Blocks should have `BREAK` and `PLACE` autogenerated based on hardness.

**To Reproduce**
1. Any current build
2. Make new game with cheats enabled
3. Give self 1 `minecraft:iron_ore`

**Additional context**
Seems to be consistent across the two build types (1.18.2-1.19.2 and 1.19.4-1.20.1)

**Comment by Caltinor** [comment]
That is for the category not the value itself.  it's been mispelled like that since Apr 2022.   Also, break and place reqs for blocks were removed a long time ago.  this config option is actually a leftover from when I did generate reqs.  I should just remove those config options

**Comment by Caltinor** [comment]
I'm going to backlog this.  The issue with the hardness not "working" is because i'm using base hardness compared to dig speed which means only a suuuuuper hard block would ever show as having a req.  Since people push back hard against block break reqs, i'm going to backlog this in case we get a push for people wanting auto-generated block reqs.
