### ISSUE TITLE
Fireworks On Repsawn

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#405]
**Describe the bug**
Massive amount of fireworks go off when you die and respawn.

**Expected behavior**
My death to not be celebrated quite so much.

**To Reproduce**
1. Get some levels
2. Sudoku
3. See error

**Versions:**
1.20.1 (massive amount)
1.19.4 (one firework)
1.19.2 (one firework)
1.18.2 (no fireworks)

**Comment by TheTaterLord** [comment]
those silly number puzzles do indeed make me unalive myself, but yes this is easily repeatable and can cause quite a lot of lag also noticed it does it on world join aswell sometimes

**Comment by FoxMcloud5655** [comment]
Can confirm that it happens in PMMO version 1.20.1-1.2.8.

**Comment by Caltinor** [comment]
This is intended behavior. Charisma is awarded for interacting with entities. There is no specific context applied to dictate when the XP is awarded.

**Comment by FoxMcloud5655** [comment]
I'm not sure what this has to do with the fireworks...

**Comment by Caltinor** [comment]
linking the xp rework since i'm certain that will involve testing and fixing the level-up issues..

**Comment by Caltinor** [comment]
Unlinking since i think the xp refactor is going to have to be a 1.21 feature.  In any case, the logic that is firing these extra fireworks is intended to reapply attributes after a player dies.  since attributes don't persist death, the only way to give back the extra hearts, damage, speed, etc from leveling up is to trigger a skillup event on respawn.  Naturally this fires the fireworks as well.  I need to find a way to not have fireworks proc, but that might not be possible.

**Comment by Caltinor** [comment]
nvm. that was actually an easy fix
