### ISSUE TITLE
Chat Unlock Messages

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#450]
**Describe the solution you'd like**
A way to enable the feature from legacy where a skill level up shows a list of what it unlocks. Perks, tool use, maybe even block breaking. Perhaps have it configurable client side with a list of what types of things to show.

**Why is this feature needed**
So people get a better feel for what levels give as rewards as they get them.

**Describe alternatives you've considered**
Not having it (maybe have it off by default?)

**Additional context**
My cat's name is mittens.

**Comment by Caltinor** [comment]
I did ponder on this when i did the rework.  On one hand, i 100% agree with your point that it helps levels feel more significant.  On the other hand, the issue I encountered had to do with NBT items.  Since they are all one item but the NBT could have wildly different requirements, there was not clean way to include those.  I could omit them, but I was holding out for a better system of identifying NBT-configured unlocks.
