### ISSUE TITLE
Way to gain Swimming XP for swimming horizontally underwater.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#495]
**Describe the solution you'd like**
Currently there are solutions for gaining XP by moving in the Y direction (Surfacing, Diving). There are no events for gaining XP for moving in the X or Z directions. If `submerged` XP is enabled then XP is granted all the time while underwater, if it is disabled then no xp is granted for moving in the X and Z planes. 

**Why is this feature needed**
To give players XP consistently for swimming in the X and Z planes based on distance moved just like `DIVING` and `SUBMERGED`

**Describe alternatives you've considered**
Give XP Passively just for being underwater, but that doesn't feel good as they're not doing anything to "earn" the xp. Granting XP from movement seems like the best method.

**Additional context**
This is related to https://github.com/Caltinor/Project-MMO-2.0/issues/464. I do still think there is a bug there with surfacing and diving per this issue, but I turned the XP down far enough that it shouldn't matter.

**Comment by Caltinor** [comment]
even with 100xp for SUBMERGED, the player simply does not move fast enough to provide a calculatable value.  Furthermore, in most cases the player is either sprinting, or is moving ever so slightly up or down, which triggers DIVING/SURFACING respectively instead of submerged.    I even gave myself depth strider and a modified movement attribute to try and trigger enough speed to register movement big enough to show up with xp and it had no effect.

I think for your use case, you should use an AFK anti-cheese on SUBMERGED so that moving disables the anti-cheese and resumes the XP, but sitting still gives nothing.
