### ISSUE TITLE
Crash Reported - Mana And Artifice Interaction

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#497]
**Describe the bug**
Seems to be a crash bug involving [Mana And Artifice](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice) entity being right-clicked.

**Expected behavior**
No crash

**Crash Log**
[crash-2024-03-13_21.29.35-client.txt](https://github.com/Caltinor/Project-MMO-2.0/files/14595711/crash-2024-03-13_21.29.35-client.txt)

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.2.21
 - PMMO: 1.20.1-1.2.20
 - MnA: 3.0.0.10

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/753013a3-66a7-47fe-8f5c-06a92cbf5b8b

**Comment by Caltinor** [comment]
This came up once before already. Since I can't see the source code for MNA, I can't diagnose the issue. It looks like something on their end, but I cannot confirm. Hence, why I sent the last person to them.  Of the author of MNA doesn't want to share their source code I at least need them to explain what's happening and why it's pmmo's fault.

**Comment by SomewhatDamaged** [comment]
Fair enough.
