### ISSUE TITLE
Requirement-Not-Met Effects Sliding Off

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#555]
**Describe the bug**
In Peaceful mode, requirements-not-met effects apply once, then never again.
In Easy mode, requirements-not-met effects apply with reduced duration, and wear off before renewing.

**Expected behavior**
The effects should remain so long as you have the items equipped/held.

**To Reproduce**
1. Create new game on normal with cheats
2. Give self Diamond Sword
3. See effects sticking as usual
4. Change difficulty to Easy
5. Wait a little bit, effects start fading in and out
6. Change difficulty to Peaceful
7. Wait a little bit, effects will fade away and never come back

**Versions:**
 - Minecraft: (eg 1.20.1)
 - Loader: (eg. Forge-47.2.30)
 - PMMO: 1.20.1-1.3.22

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/d1c4d3a5-bf3a-4efe-afc2-5fb571edbb68

**Comment by Caltinor** [comment]
Using the method above as well as replicating the method using biome penalties, I am unable to reproduce the behavior.  In all tests, the effects were persistent for multiple minutes.  It might be related to newer versions of Forge.  I develop using 47.1.0 so that I can retain NeoForge compatibility.  This may be a forge bug.

**Comment by SomewhatDamaged** [comment]
New version released fixed this.

**Comment by Caltinor** [comment]
yay magic, self-resolving, bugs!!
