### ISSUE TITLE
Multiplayer double jump

### ISSUE THREAD

**Issue by dude4123** [Caltinor/Project-MMO-2.0#63]
i have a dedicated server and it only has the "pmmo mod"
when jumping jumps 2 blocks and slows acceleration when running

everything works fine in single player

just jump and nothing more

when it is a space of 2 blocks and I jump the character jumps several times repeatedly
could it be the fault of my server? It doesn't have a single mod
neither datapacks

Version
minecraft 1.18.2
forge 40.1.68
pmmo 1.18.2-3.69.11

**Comment by Caltinor** [comment]
This is a known issue and cannot be fixed.  The best option is to remove these sections from `perks.json` on the server.
![px2w0s5](https://user-images.githubusercontent.com/62700786/183540166-90f2f060-e28a-42a0-a794-cbb42403b176.png)

The reason for this is that jumping is handled client side but the perks were only implemented server side in this version of PMMO.  to implement them client side would have been a major overhaul and since I was already rewriting the mod from the ground up it made more sense just to wait.
