### ISSUE TITLE
Keep getting random 3 second speed boost without doing anything. 1.16.5

### ISSUE THREAD

**Issue by Bookstore3** [Caltinor/Project-MMO-2.0#72]
**Describe the bug**
I keep getting speed boost for three seconds over and over without even leveling up.

I have confirmed this Project MMO has caused the issue by removing all the other mod and only leaving this mod.

This keeps turning on and off constantly to the point it's unplayable.

I am on a 1.16.5 version and used latest 1.16.5 version of Project MMO

**Comment by Bookstore3** [comment]
Thanks for the fast response.

I am playing singleplayer and I believe I was at plains biome. Though I have noticed this issue even when I was on deep ocean.

If this is a biome boost related is there config setting that I can turn it off?

**Comment by Caltinor** [comment]
Yes, via datapack, but is shouldn't be turning on and off like you described. It should be resetting every half second so that you have a constant boost that fades a few seconds after leaving the biome. 

Either we have a bug with how often the effect is applied, or your game is lagging excessively and the server thread can't keep up.

**Comment by Bookstore3** [comment]
I see.. Maybe my game is lagging.. Anyways thanks for the reply..! :D

**Comment by cikovladimka** [comment]
Hello! The problem occurred again on versions immediately after mmo-1.20.1-1.1.3
But another problem follows - hieroglyphs in Russian, which are solved by cutting out Russian from the mod..
Therefore, for those who encounter this, including for the author’s awareness, there is no problem up to version mmo-1.20.1-1.1.3 inclusive
